services:
  app:
    image: 967103305191.dkr.ecr.ap-northeast-2.amazonaws.com/auction-market:latest
#    image: ${APP_IMAGE_URI}
    container_name: auction-market
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    depends_on: # 각 DB가 healthcheck 가 된 후 app 시작
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always
    networks:
      - auction-market-network

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: test
    volumes:
      # 데이터를 영구적으로 저장하기 위해 볼륨 => 데이터 영속성
      - mysql_data_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - auction-market-network

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck: # Redis 서버가 PING 에 응답하는지 확인 => 정상적으로 동작하면 핑-퐁 응답함
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # mysql 는 시작/초기화가 길어서 30s 주고, 레디스는 짧아서 10s 줌
    restart: always
    networks:
      - auction-market-network

networks:
  auction-market-network:
    driver: bridge

# Named Volumes 사용
volumes:
  mysql_data_volume:

