spring:
  application:
    name: AuctionMarket

    # JPA, Hibernate 설정
  jpa:
    hibernate:
#      ddl-auto: validate
      ddl-auto: create
#      ddl-auto: update
#      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

    # 기존 MySQL 연결 설정 => EC2에서 의존받게 변경 (url, 유저네임은 그냥 여기서 사용, 비밀번호만 .env 의존)
  datasource:
    url: jdbc:mysql://localhost:3306/auction_market
    username: root
    password: 2031
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 기존 Redis 설정 => EC2에서 의존받게 변경
  data:
    redis:
      host: localhost
      port: 6379

  #  # JWT 설정
  #  jwt:
  #    secret:
  #      key: 2SELqxKueQ4uZpyzvqXECg00k9vSt7ioId2TwvyRDZk=
