spring.application.name=AuctionMarket
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
#spring.datasource.url=jdbc:mysql://localhost:3306/auction_market?serverTimezone=Asia/Seoul
spring.datasource.username=${DB_USERNAME}
#spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=false
jwt.secret.key=VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

##??? ??
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

#jwt.secret.key=7JWI64WV7ZWY7IS47JqU6rCQ7IKs7ZW07JqU7J6Y7J6I7Ja07JqU
WEBSOCKET.SERVER.URL=http://localhost:8081

##redis ??
spring.data.redis.host=localhost
spring.data.redis.port=6379
#spring.cache.type=none

##elastic search
spring.elasticsearch.uris = http://localhost:9200

##open search
opensearch.url = https://search-auction-search-test-4blv2xe4kahf56hilp7f5ygbde.ap-northeast-2.es.amazonaws.com
opensearch.username=team2
opensearch.password=Team2Sparta**

#AWS S3
cloud.aws.credentials.access-key=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
cloud.aws.region=${CLOUD_AWS_REGION}
cloud.aws.s3.bucket=${CLOUD_AWS_S3_BUCKET}

#AWS CloudFront
cloud.aws.cloudfront.domain=${CLOUD_AWS_CLOUDFRONT_DOMAIN}

#??? ??? ?? ?? ??
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# bigquery dataset
spring.cloud.gcp.bigquery.dataset-name=${GCP_BIGQUERY_DATASET_NAME}

# BigQuery Configuration
gcp.bigquery.project-id=${GCP_BIGQUERY_PROJECT_ID}
gcp.bigquery.dataset-name=${GCP_BIGQUERY_DATASET_NAME}
gcp.bigquery.table-name=${GCP_BIGQUERY_TABLE_NAME}

#logging.level.root=DEBUG