spring.application.name=AuctionMarket
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

jwt.secret.key=${JWT.SECRET.KEY}

#WEBSOCKET.SERVER.URL=http://localhost:8081

##redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

##elastic search
spring.elasticsearch.uris = http://localhost:9200

##open search
opensearch.url=https://search-auction-search-5zla3a7zjinciwb5nvnw4uhrdq.ap-northeast-2.es.amazonaws.com
opensearch.username=team2
opensearch.password=Team2****

#AWS S3
cloud.aws.credentials.access-key=${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
cloud.aws.region=${CLOUD_AWS_REGION}
cloud.aws.s3.bucket=${CLOUD_AWS_S3_BUCKET}

#AWS CloudFront
cloud.aws.cloudfront.domain=${CLOUD_AWS_CLOUDFRONT_DOMAIN}

#image file capacity settings
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# bigquery dataset
spring.cloud.gcp.bigquery.dataset-name=${GCP_BIGQUERY_DATASET_NAME}

# BigQuery Configuration
gcp.bigquery.project-id=${GCP_BIGQUERY_PROJECT_ID}
gcp.bigquery.dataset-name=${GCP_BIGQUERY_DATASET_NAME}
gcp.bigquery.table-name=${GCP_BIGQUERY_TABLE_NAME}