input {
  jdbc {
    jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-j-9.3.0.jar"
    jdbc_connection_string => "jdbc:mysql://host.docker.internal:3306/AuctionMarket"
    jdbc_user => "root"
    jdbc_password => "spartaSQL@3306"
    schedule => "* * * * *"  # 매 분마다 실행
    statement => "SELECT * FROM log WHERE created_at > :sql_last_value"
    use_column_value => true
    tracking_column => "created_at"
    jdbc_paging_enabled => true
    jdbc_page_size => 1000
    last_run_metadata_path => "/usr/share/logstash/logstash_metadata/logs_last_run.yml"
  }
}

filter {
  mutate {
    rename => {
      "created_at" => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "mysql-logs"
  }
  stdout { codec => rubydebug }
}