name: Java CI/CD with Gradle, Docker, AWS ECR & EC2 App Deployment (using RDS & ElastiCache)

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - main
      - dev
      - feat/cicd

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY_URI }}
  APP_CONTAINER_NAME: auction-market-app

jobs:
  build-and-push-image:
    name: 작업1 - 도커 이미지 빌드 + ECR 푸시
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.build-image.outputs.image }}
      image_uri_123456789: ${{ steps.build-image-123456789.outputs.image }}

#    services:
#      mysql:
#        image: mysql:8.0
#        env:
#          MYSQL_ROOT_PASSWORD: 1234
#          MYSQL_DATABASE: auction_market
#        ports:
#          - 3306:3306
#        options: >-
#          --health-cmd="mysqladmin ping --silent"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=5
#      redis:
#        image: redis:latest
#        ports:
#          - 6379:6379
#        options: >-
#          --health-cmd="redis-cli -h 127.0.0.1 ping"
#          --health-interval=10s
#          --health-timeout=5s
#          --health-retries=5

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: gradlew 실행 권한 부여
        run: chmod +x ./gradlew

      - name: Gradle 캐시 설정
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle 테스트 실행
#        env:
#          SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/auction_market
#          SPRING_DATASOURCE_USERNAME: root
#          SPRING_DATASOURCE_PASSWORD: 1234
#          SPRING_DATA_REDIS_HOST: 127.0.0.1
#          SPRING_DATA_REDIS_PORT: 6379
        run: ./gradlew test

      - name: AWS IAM 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: AWS ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 빌드 + 태그 + ECR 에 푸시
        id: build-image
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          FULL_IMAGE_NAME=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "이미지 빌드: $FULL_IMAGE_NAME"
          docker build -t $FULL_IMAGE_NAME .
          echo "이미지 PUSH: $FULL_IMAGE_NAME"
          docker push $FULL_IMAGE_NAME
          echo "image=$FULL_IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "GITHUB_OUTPUT 값 = $GITHUB_OUTPUT"

      - name: 빌드 디버깅용 123456789 아웃풋
        id: build-image-123456789
        if: github.event_name == 'push'
        run: |
          echo "image=123456789" >> $GITHUB_OUTPUT
          echo "123456789의 GITHUB_OUTPUT 값 = $GITHUB_OUTPUT"

      - name: 도커 이미지 빌드 결과 디버깅
        run: |
          echo "🔔 빌드 결과 도커 이미지 = '${{ steps.build-image.outputs.image }}'"
          echo "🔔 빌드 결과 도커 이미지 직접 구성 = '${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY_URI }}:${{ github.sha }}'"

  deploy-app-to-ec2:
    name: 작업2 - EC2 인스턴스에 SSH 로 배포
    runs-on: ubuntu-latest
    # 의존성 설정 => build-and-push-image 완료 후 실행
    needs: build-and-push-image
    # push 일 때만 실행 => PR 시에는 실행 안 함
    if: github.event_name == 'push'

    steps:

      - name: AWS IAM 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: AWS ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: 도커 이미지 빌드 결과 디버깅 (deploy-app-to-ec2 작업)
        run: |
          echo "🔔 빌드 결과 도커 이미지 = '${{ needs.build-and-push-image.outputs.image_uri }}'"
          echo "🔔 빌드 결과 도커 이미지 직접 구성 = '${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY_URI }}:${{ github.sha }}'"
          
      - name: Check file paths before tar
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing root directory contents:"
          ls -la
          echo "Listing filebeat directory contents (if exists):"
          ls -la filebeat/ || echo "filebeat directory not found"    

      - name: 필요한 배포 파일 준비 (tar 압축)
        run: tar -czvf deploy_package.tar.gz docker-compose.yml filebeat/filebeat.yml

      - name: EC2에 배포 파일 복사
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "deploy_package.tar.gz"
          target: "/home/${{ secrets.EC2_SSH_USER }}/" # EC2 홈 디렉토리 등에 복사

      - name: SSH 를 통해 EC2 인스턴스에 접속하여 배포 스크립트 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |                  
            echo "변수에 직접 할당 시작"        
            ECR_REGISTRY='${{ steps.login-ecr.outputs.registry }}'            
            APP_IMAGE_URI='${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY_URI }}:${{ github.sha }}'
            AWS_REGION='${{ env.AWS_REGION }}'
            
            APP_CONTAINER_NAME='${{ env.APP_CONTAINER_NAME }}'
            
            SPRING_PROFILES_ACTIVE='dev'
            SPRING_DATASOURCE_URL='${{ secrets.RDS_URL }}'
            SPRING_DATASOURCE_USERNAME='${{ secrets.RDS_USERNAME }}'
            SPRING_DATASOURCE_PASSWORD='${{ secrets.RDS_PASSWORD }}'
            SPRING_DATA_REDIS_HOST='${{ secrets.ELASTICACHE_HOST }}'
            SPRING_DATA_REDIS_PORT='${{ secrets.ELASTICACHE_PORT }}'
            
            JWT_SECRET_KEY='2SELqxKueQ4uZpyzvqXECg00k9vSt7ioId2TwvyRDZk=' # 테스트 위해 임시로 하드코딩함
            LOGSTASH_EC2_PRIVATE_IP='${{ secrets.LOGSTASH_EC2_PRIVATE_IP }}'
          
            echo "=====================" 
            
            echo "변수에 직접 할당한 후, 변수 할당 값 확인 디버깅"
            echo "SPRING_PROFILES_ACTIVE 변수 할당 값= '$SPRING_PROFILES_ACTIVE'"
            echo "ECR_REGISTRY 변수 할당 값= '$ECR_REGISTRY'"
            echo "APP_IMAGE_URI 변수 할당 값= '$APP_IMAGE_URI'"
            echo "AWS_REGION 변수 할당 값= '$AWS_REGION'"
            echo "APP_CONTAINER_NAME 변수 할당 값= '$APP_CONTAINER_NAME'"
            echo "SPRING_DATASOURCE_URL 변수 할당 값= '$SPRING_DATASOURCE_URL'"
            echo "SPRING_DATASOURCE_USERNAME 변수 할당 값= '$SPRING_DATASOURCE_USERNAME'"
            echo "SPRING_DATASOURCE_PASSWORD 변수 할당 값= '$SPRING_DATASOURCE_PASSWORD'"
            echo "SPRING_DATA_REDIS_HOST 변수 할당 값= '$SPRING_DATA_REDIS_HOST'"
            echo "SPRING_DATA_REDIS_PORT 변수 할당 값= '$SPRING_DATA_REDIS_PORT'"
            
            echo "JWT_SECRET_KEY 변수 할당 값= '$JWT_SECRET_KEY'"
            echo "LOGSTASH_EC2_PRIVATE_IP 변수 할당 값= '$LOGSTASH_EC2_PRIVATE_IP'"
            
            echo "=====================" 
            
            echo "변수 export"
            export ECR_REGISTRY
            export APP_IMAGE_URI
            export AWS_REGION
            export APP_CONTAINER_NAME
            export SPRING_PROFILES_ACTIVE
            export SPRING_DATASOURCE_URL
            export SPRING_DATASOURCE_USERNAME
            export SPRING_DATASOURCE_PASSWORD
            export SPRING_DATA_REDIS_HOST
            export SPRING_DATA_REDIS_PORT
            export JWT_SECRET_KEY
            export LOGSTASH_EC2_PRIVATE_IP
            
            echo "====================="                   
        
            echo "배포 디렉토리 생성 및 이동"
            mkdir -p deploy
            cd deploy
            
            echo "압축 해제"
            tar -xzvf ../deploy_package.tar.gz
            
            echo "Logstash IP 주소 filebeat.yml 에 적용"
            sed -i "s/LOGSTASH_EC2_PRIVATE_IP/${LOGSTASH_EC2_PRIVATE_IP}/g" filebeat.yml
          
            echo "====================="
            
            
            echo "EC2 인스턴스에 docker-compose 설치 확인"
            if ! docker compose version &> /dev/null
            then
              echo "docker compose 를 찾을 수 없습니다. 설치하는 중..."
              sudo yum install docker-compose-plugin -y
            else
              echo "docker compose 를 찾았습니다."
            fi
            
          
            echo "=====================" 
            
            # ECR 로그인
            echo "ECR 로그인 중..."
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
            if [ $? -ne 0 ]; then
              echo "ECR 로그인 실패"
              exit 1
            fi
            echo "ECR 로그인 성공."
            
            echo "=====================" 
                    
            # 최신 이미지 받기
            echo "최신 이미지 받는 중...: ${APP_IMAGE_URI}"
            docker pull ${APP_IMAGE_URI}
            if [ $? -ne 0 ]; then
              echo "이미지 받기 실패: ${APP_IMAGE_URI}"
              exit 1
            fi
            echo "이미지 받기 완료: ${APP_IMAGE_URI}"
            
            echo "=====================" 
            
            echo "최신 Filebeat 이미지 받는 중..."
            docker pull docker.elastic.co/beats/filebeat:8.17.4
            
            echo "=====================" 
            
            echo "기존 스택 중지 및 제거 시도..."
            docker-compose down --volumes --remove-orphans || true
            
            echo "=====================" 
            
            echo "Docker Compose 스택 실행 중..."
            docker-compose up -d
            if [ $? -ne 0 ]; then echo "Docker Compose 실행 실패"; exit 1; fi
            
            echo "=====================" 
                       
            # 오래된 Docker 이미지 정리
            echo "오래된 도커 이미지 정리 중..."
            docker image prune -af
            
            echo "=====================" 
            
            echo "배포 성공"